name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm frustrated when..."
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: "I would like to..."
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "I've also thought about..."
      
  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - OAuth Integration
        - Publishing Features
        - Analytics
        - UI/UX Improvement
        - API Enhancement
        - Documentation
        - Performance
        - Security
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my usage
        - High - Very important
        - Medium - Would be nice to have
        - Low - Just an idea
    validations:
      required: true
      
  - type: dropdown
    id: platform
    attributes:
      label: Related Platform
      description: Is this feature specific to a social media platform?
      multiple: true
      options:
        - Facebook
        - YouTube
        - TikTok
        - Instagram
        - Twitter
        - LinkedIn
        - Pinterest
        - All platforms
        - Not platform-specific
        
  - type: textarea
    id: examples
    attributes:
      label: Examples or Mockups
      description: Add any mockups, examples, or references
      placeholder: Links to similar features or mockups
      
  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: Who would benefit from this feature and how?
      placeholder: "This would help users by..."
      
  - type: checkboxes
    id: contribute
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I'm willing to submit a PR for this feature
        - label: I can help with testing
        - label: I can help with documentation
        
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
